### ISSUE TITLE
DNS Bin -Example receiving data -Receiving text  Bug

### ISSUE THREAD

**Issue by 0c0c0f** [mxcxvn/requestbin.net#1]
➜  dnslog python dnsbinclient.py -f- -d in -t-
Your token is : 6acc9ba35860b3e6fbf4
Traceback (most recent call last):
  File "dnsbinclient.py", line 122, in <module>
    for parts in read_bytes_from_outside():
  File "dnsbinclient.py", line 47, in read_bytes_from_outside
    bytes = data_from_url(message["data"])
  File "dnsbinclient.py", line 18, in data_from_url
    return "".join(url.split(".")[1:]).decode("hex")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found

**Comment by cuongmx** [comment]
In new version, we just support in web
